### ISSUE TITLE
Pointer to RubiRules predicates documentation

### ISSUE THREAD

**Issue by rljacobson** [RuleBasedIntegration/JOSS-Publication#7]
Some users will want to understand the "Condition" field in the Rubi rules produced by `Steps`. For example, what's the difference between `PolyQ` and `ProperPolyQ`? You have many of the predicates already documented, and most of the predicates that lack `::usage` messages are documented with comments. Why not export those?

Consider this a reviewer suggestion rather than a necessity.

**Comment by halirutan** [comment]
Except for the `::usage` messages I already included and some minor tweaks, this file is still the original version of Albert. The future plan is a bit more ambitious than what you suggest. Having usage messages for these function, I would like to include them in the `Steps` display so that the user instantly sees what they mean.

I have now created two issues for this. See 

- https://github.com/RuleBasedIntegration/Rubi/issues/15
- https://github.com/RuleBasedIntegration/Rubi/issues/16
